apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: grafana-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: oneclick/grafana-password
        property: password
