apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-infracost-secret
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: jenkins-infracost-secret
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: oneclick/infracost-api-key
        property: key