apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: oneclick/db-credentials
        property: DB_HOST
    - secretKey: DB_USER
      remoteRef:
        key: oneclick/db-credentials
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: oneclick/db-credentials
        property: DB_PASSWORD
