apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring

spec:
  interval: 1m

  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system

  values:
    alertmanager:
      enabled: true
      alertmanagerSpec:
        configSecret: alertmanager-prometheus-kube-prometheus-alertmanager
