apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1m

  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system

  values:
    alertmanager:
      config:
        global:
          smtp_smarthost: 'smtp.gmail.com:587'
          smtp_from: 'vaishjp2005@gmail.com'
          smtp_auth_username: 'vaishjp2005@gmail.com'
          smtp_auth_password: 'yaxppcbhbukkarsq'
          smtp_require_tls: true

        route:
          receiver: 'email-notifications'

        receivers:
        - name: 'email-notifications'
          email_configs:
          - to: 'vaishjp2005@gmail.com'
            send_resolved: true
