apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - test-alert.yaml
  - cpu-high.yaml
  - memory-high.yaml
  - crashloop.yaml
  - pods-down-2.yaml
  - pods-down-3.yaml
