apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: memory-high
  namespace: monitoring
  labels:
    release: prometheus

spec:
  groups:
  - name: memory.rules
    rules:
    - alert: HighMemoryUsage
      expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: High Memory Usage
        description: Memory usage is above 80%.
