apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pods-down-6
  namespace: monitoring
  labels:
    release: prometheus

spec:
  groups:
  - name: high-cpu.rules
    rules:
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{pod=~"backend.*"}[5m])) * 100 > 80
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: High CPU Usage
        description: CPU usage is above 80% for backend.
