apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vivekmemoryhigh-1
  namespace: monitoring
  labels:
    release: prometheus

spec:
  groups:
  - name: high-memory.rules
    rules:
    - alert: HighMemoryUsage
      expr: sum(container_memory_working_set_bytes{pod=~"frontend.*"}) > 500000000
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: High Memory Usage
        description: Memory usage is high for frontend.
