apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vivekcpuhigh-2
  namespace: monitoring
  labels:
    release: prometheus

spec:
  groups:
  - name: deployment-down.rules
    rules:
    - alert: DeploymentDown
      expr: kube_deployment_status_replicas_available{deployment="frontend"} < 1
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: Deployment Down
        description: Deployment frontend has no available replicas.
