frontend:
  image:
    repository: 155734788051.dkr.ecr.ap-south-1.amazonaws.com/frontend
    tag: "aa8b25f-10"
  replicas: 2
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000

backend:
  image:
    repository: 155734788051.dkr.ecr.ap-south-1.amazonaws.com/backend
    tag: "aa8b25f-10"
  replicas: 2
  service:
    type: ClusterIP
    port: 3001
