apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - apps.yaml
  - alerting.yaml
  - monitoring-config.yaml
  - external-secrets-config.yaml
  - jenkins-secret.yaml