apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cluster-autoscaler
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: flux-system
  values:
    cloudProvider: aws
    autoDiscovery:
      clusterName: "oneclick-cluster"
    awsRegion: ap-south-1
    rbac:
      serviceAccount:
        create: true
        name: cluster-autoscaler
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::286836106281:role/oneclick-cluster-autoscaler-irsa"
    extraArgs:
      balance-similar-node-groups: true
      skip-nodes-with-system-pods: false
