apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cluster-autoscaler
      version: "9.57.0"
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: flux-system
  values:
    autoDiscovery:
      clusterName: oneclick-cluster
    awsRegion: ap-south-1
    cloudProvider: aws
    rbac:
      create: true
      serviceAccount:
        create: true
        name: cluster-autoscaler
        annotations: {}
    extraArgs:
      logtostderr: true
      stderrthreshold: info
      v: 4
      skip-nodes-with-local-storage: false
      expander: least-waste
      balance-similar-node-groups: true
      skip-nodes-with-system-pods: false
    extraEnv:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: cluster-autoscaler-aws-creds
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: cluster-autoscaler-aws-creds
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_REGION
        value: ap-south-1
