apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8sgpt
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.k8sgpt.ai/
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8sgpt-operator-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8sgpt-operator
  namespace: k8sgpt-operator-system
spec:
  interval: 10m
  chart:
    spec:
      chart: k8sgpt-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: k8sgpt
        namespace: flux-system
  values: {}