apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oneclick
  namespace: default

spec:
  interval: 1m

  chart:
    spec:
      chart: ./helm/oneclick
      sourceRef:
        kind: GitRepository
        name: oneclick
        namespace: flux-system
