apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: oneclick
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/vivekbhat07/oneclick-gitops
  ref:
    branch: main
