apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - oneclick
  - monitoring
  - metrics-server
  - autoscaling
  - cluster-autoscaler
  - ingress-nginx
  - external-secrets
  - jenkins
  - jenkins-rbac
  - ollama
  - k8sgpt-operator
  - jenkins-secret
  - k8sgpt-config